server:
  port: 8081

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    username: root
    password: Aacs_3314
    url: jdbc:mysql://43.139.14.96:3306/Web?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.example.forumbackend.domain, com.example.forumbackend.utils



logging:
  file:
    path: srp.log
  level:
    com:
      example:
        mapper: debug
        netty: trace
