CREATE TABLE user(
uid BIGINT AUTO_INCREMENT PRIMARY KEY,
username VARCHAR(20),
password VARCHAR(20)
);


CREATE TABLE post(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
uid BIGINT,
username VARCHAR(20),
time VARCHAR(30),
title VARCHAR(10),
content VARCHAR(100),
FOREIGN KEY (uid) REFERENCES user(uid)
)